### PR TITLE
Made function to send cell data CAN msgs

### PR DESCRIPTION
**Pull request by HamzaIqbal69**
Issue #158 

Added a function to broadcast cell data
Goes through each cell and sends a message for each one
*Note: the first 4 bits of the message are the chip and the next 4 bits are the cell

## Describe your changes

Changes made
-
-
-

### CODE REVIEW

**Review by nwdepatie — APPROVED** [review]
I think I'm good w/ it, @dyldonahue double check formatting

**Comment by nwdepatie** [comment]
Also fix merge conflicts pretty pls

**Review by mccauleyma — CHANGES_REQUESTED** [review]
We need to assess if this blocks the code for too long. Orion BMS would send one cell per cycle, whereas this is sending every single cell every cycle which may extend the cycle time significantly

**Comment by dyldonahue** [comment]
well we can control how often this sends, so no reason to think it has to be every cycle. in fact we had pretty much decided that implementation will involve sending less frequently than every iteration. 

formatting all looks fine to be but just wanna make sure can ID 0x07 is free and available for this

**Comment by mccauleyma** [comment]
This is not coded for that type of control though. Right now we could set this to trigger once every x seconds, but when it does trigger it sends all 72 messages back to back.
 Imo we should replicate Orion and have a counter such that we send the message every x milliseconds and each time it is sent the cell being sent increments. In this case we would need this function to just map 0-71 to what chip and cell it would be

**Comment by dyldonahue** [comment]
Closing due to concerns pointed out in the comments above. I dont think we ever will really need this data anyway, but if we do, we need to implement some sort of timing control as explained above. Noted for potential reopen at later time

**Pull request closed without merging**
