### PR TITLE
"Added Fault Status Message with changes that matt requested"

### PR DESCRIPTION
**Pull request by HamzaIqbal69**
## 112

Ticket #  -> Fix X

## Added fault status messages with the changes that matt requested

Changes made
-
-
-

### CODE REVIEW

**Review by dyldonahue — CHANGES_REQUESTED** [review]
code seems fine but we want to be merging this into develop/shepehrd-fw not main, not sure if thats a change u can make to the PR or if a new one has to be opened up

**Comment by HamzaIqbal69** [comment]
Changed it to get merged into develop

**Review by dyldonahue — APPROVED** [review]

**Comment by nwdepatie** [comment]
> Changed it to get merged into develop

Damn I didn't know you could do that lmao

**Comment by nwdepatie** [comment]
Looks pretty nice, make sure to squash and merge tho

**Pull request merged**
